<h2>Sign up using this form</h2>

<?php $this->tag->setDefaults( $data ); ?>

<?php echo $this->tag->form( 'user/login/submit' ); ?>

<div class="form-group">
	<label for="driver_licence">Driver Licence</label>
	<?php echo $this->tag->textField( [ 'driver_licence', 'required' => true, 'class' => 'form-control' ] ); ?>
	<div class="invalid-feedback">
		Field is required.
	</div>
</div>
<div class="form-group">
	<label for="password">Password</label>
	<?php echo $this->tag->passwordField( [ 'password', 'class' => 'form-control', 'required' => true ] ); ?>
	<div class="invalid-feedback">
		Field is required.
	</div>
</div>

<?php echo $this->tag->hiddenField( [ $this->security->getTokenKey(), 'value' => $this->security->getToken() ] ); ?>

<?php echo $this->tag->submitButton( [ 'Log in', 'class' => 'btn btn-primary' ] ); ?>

</form>
<script>
	( function() {
		'use strict';
		window.addEventListener( 'load', function() {
			var forms = document.getElementsByClassName( 'needs-validation' );
			var validation = Array.prototype.filter.call( forms, function( form ) {
				form.addEventListener( 'submit', function( event ) {
					if ( form.checkValidity() === false ) {
						event.preventDefault();
						event.stopPropagation();
					}
					form.classList.add( 'was-validated' );
				}, false );
			} );
		}, false );
	} )();
</script>